CREATE DATABASE ALMOMANI_PUBLIC_LIBRARY;
GO

USE ALMOMANI_PUBLIC_LIBRARY;
GO

CREATE TABLE BOOK
(
	ISBN VARCHAR(13) PRIMARY KEY,
	TITLE VARCHAR(150) NOT NULL,
	AUTH_FNAME VARCHAR(20) NOT NULL,
	AUTH_LNAME VARCHAR(20) NOT NULL,
	AUTH_MI CHAR(1),
	SECTION VARCHAR(21) NOT NULL,
	CALL_NUM VARCHAR(20),
);

CREATE TABLE BOOK_COPY
(
	BOOK_COPY_ID INT PRIMARY KEY IDENTITY(1000,1),
	ISBN VARCHAR(13) FOREIGN KEY REFERENCES BOOK(ISBN) NOT NULL,
	CONDITION VARCHAR(9) NOT NULL
);

CREATE TABLE MEMBER
(
	MEM_ID SMALLINT PRIMARY KEY IDENTITY(1000,1),
	FNAME VARCHAR(20) NOT NULL,
	MI CHAR(1),
	LNAME VARCHAR(20) NOT NULL,
	ADDR VARCHAR(200) NOT NULL,
	PHONE_NUM VARCHAR(12) NOT NULL
);

CREATE TABLE BOOK_CHECKOUT
(
	BOOK_COPY_ID INT PRIMARY KEY FOREIGN KEY REFERENCES BOOK_COPY(BOOK_COPY_ID) NOT NULL,
	MEM_ID SMALLINT FOREIGN KEY REFERENCES MEMBER(MEM_ID) NOT NULL,
	CHECK_OUT_DATE DATE NOT NULL,
	DUE_DATE DATE NOT NULL,
);